version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: 12341234   # .env파일 이용해서 수정해야함
      MYSQL_ROOT_PASSWORD: 12341234
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb

volumes:
  mysqldb_data:
