# Generated by Django 5.0.7 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_result', models.TextField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('music_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
