# Generated by Django 5.0.7 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField()),
                ('poster_url', models.URLField()),
                ('audio_url', models.URLField()),
            ],
        ),
    ]
