# Generated by Django 5.0.6 on 2024-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=1000)),
                ("music_url", models.URLField(max_length=1000)),
                ("album_cover_url", models.URLField(max_length=1000)),
                ("image_analysis", models.TextField(blank=True, null=True)),
                (
                    "psychological_interpretation",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "album",
            },
        ),
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=255)),
                ("image_analysis", models.TextField()),
                ("psychological_interpretation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "image_analysis",
                "ordering": ["-created_at"],
            },
        ),
    ]
