# Generated by Django 5.0.6 on 2024-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosterGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image_url", models.URLField(max_length=1000)),
                ("poster_url", models.URLField(max_length=1000)),
                ("image_analysis", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "poster_generation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="ImageAnalysis",
        ),
    ]
